services:
  drivent_db_test:
    image: postgres
    container_name: drivent_db_test
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env.test

  drivent_api_test:
    container_name: drivent_api_test
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - drivent_db_test
    env_file:
      - ./back-end/.env.test